### ISSUE TITLE
Can we use `Phoenix Channels` or plain `WebSockets` for sending logs?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/logs#12]
At present we are planning to use `HTTP` to send `logs` requests from the `App` e.g. `MVP`.
But if we're using a subtask / background process for sending log events, 
could we just connect that process to the `ATM` server via Channels/WebSockets and reduce the bandwidth/latency? 💭 

# Todo

+ [ ] Investigate the complexity of connecting two distinct `Phoenix` Apps via Channels/WebSockets.
+ [ ] Write-up your findings.
+ [ ] How to _secure_ the connection e.g. using a `JWT` or other token?

**Comment by ndrean** [comment]
If you cluster the 2 apps, then you can Phoenix.PubSub since the default adapter is PG2, so it is enough to subscribe, from a Channel if you want. 

I am making a little project to render a SPA embedded in a Phoenix app running in containers. I use Phoenix to secure the login process, meaning the backend takes care of providing a session cookie and a user-token so that the websocket connection is secured. I can connect a Livebook to this cluster so you can nicely `rpc` anything on the nodes, even query the database since the containers are on the same network. This works locally, I did not test this IRL :) If you are interested, I can create a repo in Dwyl, although it is not entirely finished as it is full of details.

**Comment by nelsonic** [comment]
If you can share a link to the project I’d be keen to see. 💭

**Comment by ndrean** [comment]
Sure: <https://github.com/ndrean/phoenix_solid>

**Comment by ndrean** [comment]
A quick test In a terminal: you can connect 2 nodes sharing the same cookie:

```elixir
iex --sname a --cookie secret
Mix.install([:phoenix_pubsub])
Supervisor.start_link([{Phoenix.PubSub, name: :ps}], strategy: :one_for_one)
node()
```

then
```elixir
Phoenix.PubSub.subscribe(:ps, "test")
Process.info(self(), :messages)
=> "hi"
```
Same thing in another terminal but with another "sname":

```elixir
iex --sname b --cookie secret
Mix.install([:phoenix_pubsub])
Supervisor.start_link([{Phoenix.PubSub, name: :ps}], strategy: :one_for_one)
Node.connect( <-- the result of node() of the other terminal)
```

then 
```
Phoenix.PubSub.broadcast(:ps, "test", "hi")
```

**Comment by ndrean** [comment]
I am paraphrasing the doc. A `channel` is only between the browser and the backend of an app, not between apps. The "main" socket is secured via CSRF-tokens, thus once per session. The user token (for a dedicated process or piece of dataà, it is secured firstly with `wss` to avoid data leakage, but also using a "user_token" . The server generates it once per session with  a `Phoenix.Token` with a key related to the user; normally `user.id`. You save it in the `session`,  so it is available "on first mount" for LiveView, or in the `conn` if you stay Phoenix. You pass this token to the Javascript via the DOM (just like `dataset`) by an assign (`conn` or `socket`).  More precisely, you put it into a `<script>` tag for the browser to execute it, thus reading the token. Then you can attach it to a user socket client-side, so it is passed in the query string of the WS connection. The back-end side of a Channel reads the params in the `join` callback. There, you "detockenize" the token with `Phoenix.Token.verify`, meaning you check it is a valid token. You get the "user.id" as a result (if you used this). On the other side, if you save the token in the database, then you can query for a user_id, thus checking if they agree, thus accepting the connection.  Note that you don't have access to `conn` nor `session` in a channel (ws are vulnerable to cross-origin attack). WS are also vulnerable to DOS attack, drowning the process. Luckily, Channels are Genservers, thus isolated, so you only lose this, normally. Also, WS like HTTP is plain text, so the payload needs to be sanitized, but the transport protocol takes care of this. In short, a nice piece of software.

**Comment by ndrean** [comment]
This a nice reference about security things, if you have problems to sleep....
<https://cheatsheetseries.owasp.org/index.html>
